<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            array('name' => 'English', 'code' => 'en'),
            array('name' => 'Afar', 'code' => 'aa'),
            array('name' => 'Abkhazian', 'code' => 'ab'),
            array('name' => 'Afrikaans', 'code' => 'af'),
            array('name' => 'Amharic', 'code' => 'am'),
            array('name' => 'Arabic', 'code' => 'ar'),
            array('name' => 'Assamese', 'code' => 'as'),
            array('name' => 'Aymara', 'code' => 'ay'),
            array('name' => 'Azerbaijani', 'code' => 'az'),
            array('name' => 'Bashkir', 'code' => 'ba'),
            array('name' => 'Belarusian', 'code' => 'be'),
            array('name' => 'Bulgarian', 'code' => 'bg'),
            array('name' => 'Bihari', 'code' => 'bh'),
            array('name' => 'Bislama', 'code' => 'bi'),
            array('name' => 'Bengali/Bangla', 'code' => 'bn'),
            array('name' => 'Tibetan', 'code' => 'bo'),
            array('name' => 'Breton', 'code' => 'br'),
            array('name' => 'Catalan', 'code' => 'ca'),
            array('name' => 'Corsican', 'code' => 'co'),
            array('name' => 'Czech', 'code' => 'cs'),
            array('name' => 'Welsh', 'code' => 'cy'),
            array('name' => 'Danish', 'code' => 'da'),
            array('name' => 'German', 'code' => 'de'),
            array('name' => 'Bhutani', 'code' => 'dz'),
            array('name' => 'Greek', 'code' => 'el'),
            array('name' => 'Esperanto', 'code' => 'eo'),
            array('name' => 'Spanish', 'code' => 'es'),
            array('name' => 'Estonian', 'code' => 'et'),
            array('name' => 'Basque', 'code' => 'eu'),
            array('name' => 'Persian', 'code' => 'fa'),
            array('name' => 'Finnish', 'code' => 'fi'),
            array('name' => 'Fiji', 'code' => 'fj'),
            array('name' => 'Faeroese', 'code' => 'fo'),
            array('name' => 'French', 'code' => 'fr'),
            array('name' => 'Frisian', 'code' => 'fy'),
            array('name' => 'Irish', 'code' => 'ga'),
            array('name' => 'Scots/Gaelic', 'code' => 'gd'),
            array('name' => 'Galician', 'code' => 'gl'),
            array('name' => 'Guarani', 'code' => 'gn'),
            array('name' => 'Gujarati', 'code' => 'gu'),
            array('name' => 'Hausa', 'code' => 'ha'),
            array('name' => 'Hindi', 'code' => 'hi'),
            array('name' => 'Croatian', 'code' => 'hr'),
            array('name' => 'Hungarian', 'code' => 'hu'),
            array('name' => 'Armenian', 'code' => 'hy'),
            array('name' => 'Interlingua', 'code' => 'ia'),
            array('name' => 'Interlingue', 'code' => 'ie'),
            array('name' => 'Inupiak', 'code' => 'ik'),
            array('name' => 'Indonesian', 'code' => 'in'),
            array('name' => 'Icelandic', 'code' => 'is'),
            array('name' => 'Italian', 'code' => 'it'),
            array('name' => 'Hebrew', 'code' => 'iw'),
            array('name' => 'Japanese', 'code' => 'ja'),
            array('name' => 'Yiddish', 'code' => 'ji'),
            array('name' => 'Javanese', 'code' => 'jw'),
            array('name' => 'Georgian', 'code' => 'ka'),
            array('name' => 'Kazakh', 'code' => 'kk'),
            array('name' => 'Greenlandic', 'code' => 'kl'),
            array('name' => 'Cambodian', 'code' => 'km'),
            array('name' => 'Kannada', 'code' => 'kn'),
            array('name' => 'Korean', 'code' => 'ko'),
            array('name' => 'Kashmiri', 'code' => 'ks'),
            array('name' => 'Kurdish', 'code' => 'ku'),
            array('name' => 'Kirghiz', 'code' => 'ky'),
            array('name' => 'Latin', 'code' => 'la'),
            array('name' => 'Lingala', 'code' => 'ln'),
            array('name' => 'Laothian', 'code' => 'lo'),
            array('name' => 'Lithuanian', 'code' => 'lt'),
            array('name' => 'Latvian/Lettish', 'code' => 'lv'),
            array('name' => 'Malagasy', 'code' => 'mg'),
            array('name' => 'Maori', 'code' => 'mi'),
            array('name' => 'Macedonian', 'code' => 'mk'),
            array('name' => 'Malayalam', 'code' => 'ml'),
            array('name' => 'Mongolian', 'code' => 'mn'),
            array('name' => 'Moldavian', 'code' => 'mo'),
            array('name' => 'Marathi', 'code' => 'mr'),
            array('name' => 'Malay', 'code' => 'ms'),
            array('name' => 'Maltese', 'code' => 'mt'),
            array('name' => 'Burmese', 'code' => 'my'),
            array('name' => 'Nauru', 'code' => 'na'),
            array('name' => 'Nepali', 'code' => 'ne'),
            array('name' => 'Dutch', 'code' => 'nl'),
            array('name' => 'Norwegian', 'code' => 'no'),
            array('name' => 'Occitan', 'code' => 'oc'),
            array('name' => '(Afan)/Oromoor/Oriya', 'code' => 'om'),
            array('name' => 'Punjabi', 'code' => 'pa'),
            array('name' => 'Polish', 'code' => 'pl'),
            array('name' => 'Pashto/Pushto', 'code' => 'ps'),
            array('name' => 'Portuguese', 'code' => 'pt'),
            array('name' => 'Quechua', 'code' => 'qu'),
            array('name' => 'Rhaeto-Romance', 'code' => 'rm'),
            array('name' => 'Kirundi', 'code' => 'rn'),
            array('name' => 'Romanian', 'code' => 'ro'),
            array('name' => 'Russian', 'code' => 'ru'),
            array('name' => 'Kinyarwanda', 'code' => 'rw'),
            array('name' => 'Sanskrit', 'code' => 'sa'),
            array('name' => 'Sindhi', 'code' => 'sd'),
            array('name' => 'Sangro', 'code' => 'sg'),
            array('name' => 'Serbo-Croatian', 'code' => 'sh'),
            array('name' => 'Singhalese', 'code' => 'si'),
            array('name' => 'Slovak', 'code' => 'sk'),
            array('name' => 'Slovenian', 'code' => 'sl'),
            array('name' => 'Samoan', 'code' => 'sm'),
            array('name' => 'Shona', 'code' => 'sn'),
            array('name' => 'Somali', 'code' => 'so'),
            array('name' => 'Albanian', 'code' => 'sq'),
            array('name' => 'Serbian', 'code' => 'sr'),
            array('name' => 'Siswati', 'code' => 'ss'),
            array('name' => 'Sesotho', 'code' => 'st'),
            array('name' => 'Sundanese', 'code' => 'su'),
            array('name' => 'Swedish', 'code' => 'sv'),
            array('name' => 'Swahili', 'code' => 'sw'),
            array('name' => 'Tamil', 'code' => 'ta'),
            array('name' => 'Telugu', 'code' => 'te'),
            array('name' => 'Tajik', 'code' => 'tg'),
            array('name' => 'Thai', 'code' => 'th'),
            array('name' => 'Tigrinya', 'code' => 'ti'),
            array('name' => 'Turkmen', 'code' => 'tk'),
            array('name' => 'Tagalog', 'code' => 'tl'),
            array('name' => 'Setswana', 'code' => 'tn'),
            array('name' => 'Tonga', 'code' => 'to'),
            array('name' => 'Turkish', 'code' => 'tr'),
            array('name' => 'Tsonga', 'code' => 'ts'),
            array('name' => 'Tatar', 'code' => 'tt'),
            array('name' => 'Twi', 'code' => 'tw'),
            array('name' => 'Ukrainian', 'code' => 'uk'),
            array('name' => 'Urdu', 'code' => 'ur'),
            array('name' => 'Uzbek', 'code' => 'uz'),
            array('name' => 'Vietnamese', 'code' => 'vi'),
            array('name' => 'Volapuk', 'code' => 'vo'),
            array('name' => 'Wolof', 'code' => 'wo'),
            array('name' => 'Xhosa', 'code' => 'xh'),
            array('name' => 'Yoruba', 'code' => 'yo'),
            array('name' => 'Chinese', 'code' => 'zh'),
            array('name' => 'Zulu', 'code' => 'zu'),

        );

        DB::table('languages')->insert($data);
    }
}
